site_name: MDP
site_author: Grey Haven
site_description: Markdown Data Package (MDP): A global standard file specification for document management
repo_name: mdp
repo_url: https://github.com/greyhaven-ai/mdp/
site_url: https://markdowndatapack.org/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 Datapack 
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    theme:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: black
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  custom_dir: docs/overrides
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: jxnl 
      repo: instructor
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Home: 'index.md'
  - Specification:
    - Overview: 'specification/mdp_specification.md'
    - Standard Proposal: 'specification/mdp_standard_proposal.md'
    - Schema: 'specification/mdp_schema.json'
    - OpenAPI: 'specification/mdp_openapi.yaml'
    - Implementation Examples: 'specification/mdp_implementation_examples.md'
  - Core Concepts:
    - Versioning: 'concepts/versioning.md'
    - Conflict Resolution: 'concepts/conflict_resolution.md'
    - Schema Validation: 'concepts/schema_validation.md'
    - Collection ID Types: 'concepts/collection_id_types.md'
  - Integration:
    - Installation: 'integration/installation.md'
    - Python API: 'integration/python_api.md'
    - IPFS: 'integration/ipfs.md'
    - Language Server Protocol: 'integration/lsp.md'
    - Validation: 'integration/validation.md'
  - CLI Reference:
    - Tools: 'cli/tools.md'
  - Community:
    - Overview: 'community/index.md'
    - Contributing:
      - Guidelines: 'community/contributing.md'
      - Website: 'specification/mdp_website.md'
  - User Guide:
    - Basic Usage: 'user-guide/basic-usage.md'
    - Advanced Features: 'user-guide/advanced-features.md'
    - Security & Sharing: 'user-guide/security-sharing.md'
    - Best Practices: 'user-guide/best-practices.md'
  - Examples:
    - Overview: 'examples/index.md'
    - Basic Examples: 
      - Simple Document: 'examples/basic/simple-document.md'
      - Document Parsing: 'examples/basic/document-parsing.md'
    - Metadata Examples:
      - Standard Metadata: 'examples/metadata/standard-metadata.md'
      - Custom Metadata: 'examples/metadata/custom-metadata.md'
    - Context Examples:
      - Adding Context: 'examples/context/adding-context.md'
      - Context Processing: 'examples/context/context-processing.md'
    - Relationship Examples:
      - Document Relationships: 'examples/relationships/document-relationships.md'
      - Cross-referencing: 'examples/relationships/cross-referencing.md'
  - API Reference:
    - Core API: 'api/core.md'
    - Document API: 'api/document.md'
    - Metadata API: 'api/metadata.md'
    - Context API: 'api/context.md'
  - CLI Reference:
    - Commands Overview: 'cli/index.md'
    - Document Commands: 'cli/document-commands.md'
    - Utility Commands: 'cli/utility-commands.md'
  - Support:
    - FAQ: 'support/faq.md'
    - Troubleshooting: 'support/troubleshooting.md'
    - Help Resources: 'help.md'

plugins:
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
  - blog:
      enabled: !ENV CI
      blog_dir: "blog"
      blog_toc: true
      post_dir: blog/posts
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
      enabled: !ENV [CI, false]
extra:
  analytics:
    provider: google
    property: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/greyhaven-ai/mdp
copyright: Copyright &copy; 2024 Grey Haven, LLC
